### Build with:
###   npm run build -- ttf-unhinted::Begriffsschrift --jCmd=1

[buildPlans.Begriffsschrift]
family = "Begriffsschrift"
spacing = "normal"
serifs = "sans"
exportGlyphNames = true

[buildPlans.Begriffsschrift.ligations]
inherits = "default-calt"

[buildPlans.Begriffsschrift.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Begriffsschrift.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Begriffsschrift.widths.Normal]
shape = 500
menu = 5
css = "normal"
