[[projects]]
id = "FFL_Foundation"
url = "https://github.com/FormalizedFormalLogic/Foundation"
branch = "master"
dir = "Foundation"

[[projects]]
id = "Mathlib"
url = "https://github.com/leanprover-community/mathlib4"
branch = "master"
dir = "Mathlib"

[[projects]]
id = "Physlib"
url = "https://github.com/leanprover-community/physlib"
branch = "master"
dir = "Physlib"

[[projects]]
id = "CSlib"
url = "https://github.com/leanprover/cslib"
branch = "main"
dir = "Cslib"
