name: "Dev Daily Build"
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running manually"
        required: false
        default: "Manual check"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build ${{ matrix.fontName }} font
    if: github.repository == 'be5invis/Iosevka'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fontName: ["Iosevka", "IosevkaSlab", "IosevkaAile", "IosevkaEtoile"]

    steps:
      # Checkout repository into `iosevka` sub directory
      - uses: actions/checkout@v6
        with:
          path: iosevka
          ref: dev

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install ttfautohint
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ttfautohint

      - name: Build Font ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttc::${{ matrix.fontName }}

      - name: Upload Font Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ttc-${{ matrix.fontName }}
          path: iosevka/dist/.ttc/${{ matrix.fontName }}/
